add_toggle
js-tasks-ru/htmlcss-20211021_sergey-lukashin pull request #24
Opened 2021-11-15 15:29 UTC by SarggUngart

2021-11-15 15:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-17 14:03 UTC, GSemikozov requested changes

2021-11-17 14:03 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggle__input ~ .toggle__state .toggle__control:before {
можно просто .toggle__control:before

2021-11-17 14:03 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  content: '';
тут стили почти полностью дублируем как со строки 30. Достаточно описать стили только для того что реально меняем (фон)

2021-11-17 14:03 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  cursor: inherit;
при disabled он по умолчанию будет default

2021-11-17 14:31 UTC, SarggUngart commented on 07-lection5/03-toggler/toggler.css
> +  cursor: inherit;
если его убрать, то срабатывает pointer все равно срабатывает

2021-11-17 14:31 UTC, SarggUngart commented on 07-lection5/03-toggler/toggler.css
> +  content: '';
исправил

2021-11-17 18:52 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  cursor: inherit;
но уже из другого места)
ладно, можно оставить

2021-11-17 18:53 UTC, GSemikozov approved these changes

2021-11-17 18:53 UTC, merged