add_tooltip
js-tasks-ru/htmlcss-20211021_sergey-lukashin pull request #7
Opened 2021-11-03 17:42 UTC by SarggUngart

2021-11-03 17:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-03 20:51 UTC, GSemikozov requested changes

2021-11-03 20:51 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%, -120%);
тут скорее для. последней цифры `calc(100% - 8px)`? поскольку 20% нам говорят лишь о том, что в плане отступа мы привязываемся к высоте триггера, что не очен хорошо, ведь триггером может быть любой элемент

2021-11-03 21:19 UTC, SarggUngart commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%, -120%);
Все время забываю про calc, мощная штука))
Исправил

2021-11-04 20:39 UTC, GSemikozov approved these changes

2021-11-04 20:39 UTC, merged