add_modal
js-tasks-ru/htmlcss-20211021_sergey-lukashin pull request #9
Opened 2021-11-03 21:05 UTC by SarggUngart

2021-11-03 21:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-03 21:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-03 21:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 20:33 UTC, GSemikozov requested changes

2021-11-04 20:33 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
таскать из компонента в компонент стили не надо, они все равно подключаются глобально, достаточно один раз подключить)

2021-11-04 22:25 UTC, SarggUngart commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
убрал подключение css из стилей

2021-11-06 20:36 UTC, GSemikozov approved these changes

2021-11-06 20:36 UTC, merged